[package]
name = "bruges-rs"
version = "0.1.0"
authors = ["Tony <trhallam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libbruges_rs"
crate-type = ['rlib', 'cdylib']

[dependencies]
num-traits = "0.2"
